create table if not exists hit (
    id bigint generated by default as identity not null,
    app varchar(50) not null,
    uri varchar(50) not null,
    ip varchar(50) not null,
    hit_timestamp timestamp without time zone not null
);