create table if not exists users
(
    id bigint generated by default as identity not null,
    name varchar(50) not null,
    email varchar(50) not null unique,
    CONSTRAINT pk_users PRIMARY KEY(id)
);

create table if not exists categories
(
    id bigint generated by default as identity not null,
    name varchar(50) not null unique,
    CONSTRAINT pk_categories PRIMARY KEY(id)
);

create table if not exists location
(
    id bigint generated by default as identity not null,
    lat real not null,
    lon real not null,
    CONSTRAINT pk_location PRIMARY KEY(id)
);

create table if not exists events
(
    id bigint generated by default as identity not null,
    annotation varchar(50) not null,
    category_id bigint not null,
    confirmed_requests int not null,
    created_on timestamp without time zone not null,
    description varchar(255),
    event_date timestamp without time zone not null,
    initiator_id bigint not null,
    location_id bigint not null,
    paid boolean not null,
    participant_limit int,
    published_on timestamp without time zone not null,
    request_moderation boolean not null,
    states varchar(50) not null,
    title varchar(50) not null,
    views int not null,
    CONSTRAINT pk_events PRIMARY KEY(id),
    CONSTRAINT fk_events_categories FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_events_location FOREIGN KEY (location_id) REFERENCES location (id),
    CONSTRAINT fk_events_users FOREIGN KEY (initiator_id) REFERENCES users (id)
);